<?php

use Drupal\Component\Utility\SafeMarkup;

/**
 * Implements hook_mail().
 *
 * Note that hook_mail() is not actually a hook. It is only called for a single
 * module, the module named in the first argument of MailManager::mail(). So
 * it's a callback of a type, but not a hook.
 */
function email_example_mail($key, &$message, $params) {
  // Each message is associated with a language, which may or may not be the
  // current user's selected language, depending on the type of e-mail being
  // sent. This $options array is used later in the t() calls for subject
  // and body to ensure the proper translation takes effect.
  $options = array(
    'langcode' => $message['langcode'],
  );

  switch ($key) {
    case 'contact_message':
      $from = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('E-mail sent from @site-name', array('@site-name' => $from), $options);

      $account = \Drupal::currentUser();
      $message['body'][] = t('@name sent you the following message:', array('@name' => $account->getUsername()), $options);
      $message['body'][] = SafeMarkup::checkPlain($params['message']);
      break;
  }
}

/**
 * Implements hook_mail_alter().
 */
function email_example_mail_alter(&$message) {
  $options = array(
    'langcode' => $message['langcode'],
  );

  $signature = t("\n--\nMail altered by email_example module.", array(), $options);
  if (is_array($message['body'])) {
    $message['body'][] = $signature;
  }
  else {
    // Some modules use the body as a string, erroneously.
    $message['body'] .= $signature;
  }
}
